package com.vann.model.enums;

public enum Colour {

    BLACK,
    BLACK_AND_NEON_GREEN,
    BLUE,
    COBALT_BLUE,
    DEEP_PINK,
    DEEP_SEA_GREEN,
    ELECTRIC_BLUE,
    EMERALD_GREEN,
    GREY_AND_MINT,
    HEATHER,
    LIGHT_BLUE,
    MINT,
    ORANGE,
    RED,
    SHAMROCK,
    SILVER,
    SKY_BLUE,
    VIOLET,
    WHITE_AND_YELLOW_GOLD,
    WHITE_GOLD,
    WHITE_GOLD_AND_COBALT_BLUE,
    WHITE_GOLD_AND_RED_ANIMAL_PRINT,
    WHITE_GOLD_AND_RED_PAINT,
    YELLOW_GOLD,
    YELLOW_GOLD_AND_SKY_BLUE

}
